variables:
  DEFAULT_VARIABLE: "default_value"

stages:
  - test
  - lint

test:
  stage: test
  script:
    - echo "Running tests"
    - echo "Variable value: $DEFAULT_VARIABLE"
    - pytest

lint:
  stage: lint
  script:
    - echo "Running linters"
    - isort .
    - black .
    - flake8
    - mypy .
