variables:
  DEFAULT_VARIABLE: "default_value"

stages:
  - test
  - lint

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - echo "Running tests"
    - pytest

lint:
  stage: lint
  image: python:3.11
  before_script:
    - pip install black isort flake8 mypy
  script:
    - echo "Running linters"
    - isort --check-only .
    - black --check .
    - flake8 .
    - mypy .
